name:                bit-aggregator
version:             "0.1"
license:             BSD3
author:              "Tobias Pleyer"
maintainer:          "tobi.pleyer@gmail.com"
copyright:           "2018 Tobias pleyer"

extra-source-files:
- README.md
- LICENSE

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Parse a CSV file for individual bits and aggregate them to bytes


executables:
  bit-aggregator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - bytestring
    - cassava
    - pipes
    - pipes-csv
    - pipes-bytestring
